[package]
name = "wsta"
version = "0.4.0"
authors = ["Espen Henriksen <dev@henriksen.is>"]
description = "The WebSocket Transfer Agent"

readme = "README.md"
license = "GPL-3.0"

[dependencies]
argparse = "0.2.1"
websocket = "0.17.0"
hyper = "0.9.1"
cookie = "0.2.4"
xdg = "2.0.0"
config = "0.1.3"

